### ISSUE TITLE
PatientList Class

### ISSUE THREAD

**Issue by PTamm** [CMPUT301F18T02/SymptoLogger#11]
Not sure if we want a class for list (note: not _list view_)

**Comment by Kaiwenkevinz** [comment]
Patient Class [here](https://www.draw.io/?state=%7B%22folderId%22:%221mI0ouNltfNz5RDPcr3e4Y3DTOFdvbcqQ%22,%22action%22:%22create%22,%22userId%22:%22101704973443152809829%22%7D#G16oiO9bhQynOX6UrTKwTgKY6S6Lkgx17F)
