### ISSUE TITLE
Welcome Activity UML

### ISSUE THREAD

**Issue by PTamm** [CMPUT301F18T02/SymptoLogger#12]
List user ids and allow logon

**Comment by Kaiwenkevinz** [comment]
[WelcomeActivity UML](https://www.draw.io/?state=%7B"folderId":"1mI0ouNltfNz5RDPcr3e4Y3DTOFdvbcqQ","action":"create","userId":"101704973443152809829"%7D#G1rNDDN-GK8pnpVAaWcTpV7T_I1dA69wZR)
