### ISSUE TITLE
CareProvider Class

### ISSUE THREAD

**Issue by PTamm** [CMPUT301F18T02/SymptoLogger#3]
#14 should be completed with this.

**Comment by Kaiwenkevinz** [comment]
CareProvider Class is [here](https://www.draw.io/?state=%7B%22ids%22:%5B%2219DGwLxiA8Q67egKHEZMEKueYXiJFf7sk%22%5D,%22action%22:%22open%22,%22userId%22:%22101704973443152809829%22%7D#G19DGwLxiA8Q67egKHEZMEKueYXiJFf7sk)
