### ISSUE TITLE
UserList UML

### ISSUE THREAD

**Issue by PTamm** [CMPUT301F18T02/SymptoLogger#31]
Not sure if we want a class for list (note: not _list view_)

**Comment by PTamm** [comment]
We might not need a class for this; delete it. All we need is a way of displaying a list of users when we open the app. No need for a class.

**Comment by PTamm** [comment]
We need this after all ...

**Comment by Kaiwenkevinz** [comment]
[UserList UML](https://www.draw.io/?state=%7B%22folderId%22:%221mI0ouNltfNz5RDPcr3e4Y3DTOFdvbcqQ%22,%22action%22:%22create%22,%22userId%22:%22101704973443152809829%22%7D#G1MgW61YoNAiWok3A8Tah2yFuMm_8leCCA)
