### ISSUE TITLE
Care Provider Screen Activity UML

### ISSUE THREAD

**Issue by PTamm** [CMPUT301F18T02/SymptoLogger#35]

**Comment by Kaiwenkevinz** [comment]
[Care Provider Screen Activity UML](https://www.draw.io/?state=%7B%22folderId%22:%221mI0ouNltfNz5RDPcr3e4Y3DTOFdvbcqQ%22,%22action%22:%22create%22,%22userId%22:%22101704973443152809829%22%7D#G1_wCpG1UD5GLibDSpIEP3pOCr83BOGiK7)
